### ISSUE TITLE
Deployment af Fiware Quantum Leap stack

### ISSUE THREAD

**Issue by st-randers** [Randers-Kommune-Digitalisering/vis-os2iot-data#18]
Jeg har pt. problemer med at deploy Quantum Leap med de nødvendige komponenter. 

Jeg forsøger at deploy
- Quantum Leap
- CreateDB
- Redis
- ScorpioBroker / Orion Context Broker

Jeg har forsøgt at følge denne guide: https://quantumleap.readthedocs.io/en/latest/admin/installing/#Deploy%20QuantumLeap%20In%20Kubernetes

Fra artiklen er link til [CrateDB](https://github.com/orchestracities/charts/tree/master/charts/crate) helm chart (fra samme repo findes et Quantum Leap chart) samt [Dandy Developer's chart](https://github.com/DandyDeveloper/charts/tree/master/charts/redis-ha) til Redis, som jeg har baseret mine charts på.

## Issues: 

1.  ~~Redis får jeg fejl ift. en service-account, som jeg sandsynligvis ikke har opsat korrekt.~~ **LØST**.

2. Quantum Leap har ingen logs i Argo, men står som Healthy.

CrateDB ser ud til at køre, men jeg har ikke testet yderligere.

**Comment by st-randers** [comment]
@bork91 Vil du hjælpe med at løse problemet ift. Redis?

Du må også meget gerne tage et kig på resten af konfigurationen af stacken og se om der er noget der falder dig i øjnene. Jeg har arbejdet lidt i blinde på den her..

**Comment by bork91** [comment]
Min Chart.yaml

```
apiVersion: v2
name: redis
version: 1.0.0
dependencies:
  - name: redis
    version: 17.1.7 # version 17.0.1 kan ikke bootsrappe
    repository: https://charts.bitnami.com/bitnami
```
Min values.yaml 

```
redis:
  global:
    storageClass: hcloud-volumes
  auth:
    existingSecret: redis-password

  master:
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
    persistence:
      size: 10Gi #Hetzner minimum
  replica:
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
    persistence:
      size: 10Gi #Hetzner minimum

  sentinel:
    enabled: false


  metrics:
    enabled: true
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
    serviceMonitor:
      enabled: true
sealedSecret:
  redis-password:
    encryptedData:
      redis-password: ****
```
